

# SPDX-License-Identifier: MIT
# Copyright (c) 2026-${year} WEMI Contributors
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

from typing import Literal

CUDA_X_TYPEHINT = Literal[
    "nvcc",
    "nvrtc",
    "nvtx",
    "nv-dis",
    "nvjpeg",
    "nvml",
    "nvvm",
    "nvprune",
    "nvjitlink",
    "compute-sanitizer",
    "crt",
    "cccl",
    "cuda-npp",
    "cuda",
    "cublas",
    "cufft",
    "cuobjdump",
    "cu++filt",
    "cutlass",
    "cutpi",
    "cuprofiler",
    "cusolver",
    "cusparse",
    "cusparselt",
    "cutensor",
    "cudnn",
    "cudss",
    "cuquantum",
    "cutile",
    "libcudacxx",
    "nsight-compute",
]

cuda_components_phonebook: dict[str, str | None] = {
    "nvcc":                 "cuda_nvcc",
    "nvrtc":                "cuda_cudart",
    "nvtx":                 "cuda_nvtx",
    "nv-dis":               "cuda_nvdisasm",
    "nvjpeg":               "libnvjpeg",
    "nvml":                 "cuda_nvml_dev",
    "nvvm":                 "libnvvm",
    "nvfatbin":             "libnvfatbin",
    "nvprune":              "cuda_nvprune",
    "nvjitlink":            "libnvjitlink",
    "compute-sanitizer":    None,
    "crt":                  "cuda_crt",
    "cccl":                 "cuda_cccl",
    "cuda-npp":             "libnpp",
    "cuda-gdb":             None,
    "cuobjdump":            "cuda_cuobjdump",
    "cu++filt":             "cuda_cuxxfilt",
    "cutpi":                "cuda_cupti",
    "cuda":                 "cuda",
    "cublas":               "libcublas",
    "cufft":                "libcufft",
    "cudnn":                None,
    "cudss":                None,
    "cusolver":             "libcusolver",
    "cusparse":             "libcusparse",
    "cusparselt":           "",
    "cuprofiler":           "cuda_profiler_api",
    "cutensor":             None,
    "culitho":              None,
    "cuquantum":            None,
    "cutile":               None,
    "cutlass":              r"lib/cmake/NvidiaCutlass/NvidiaCutlassConfigVersion.cmake",
    "libcudacxx":           r"lib/cmake/libcudacxx/libcudacxx-config-version.cmake",
    "nsight-compute":       "nsight_compute",
}
