# SPDX-License-Identifier: MIT
# Copyright (c) 2026-${year} WEMI Contributors
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

from pathlib import Path
import sys
from .color_string import ColorString
from typing import List, Union, Iterable, overload, TextIO
from typing_extensions import Literal
from dataclasses import dataclass

@overload
def cstring(
    text: Union[str, ColorString],
    color: Literal["SUCCESS", "WARNING", "ERROR", "HINT"],
    bold: Literal["BOLD", None] = None,
    /,
) -> ColorString: ...
@overload
def cstring(
    text: Union[str, ColorString],
    color: Union[Iterable[int], str],
    bold: Literal["BOLD", None] = None,
    /,
) -> ColorString: ...
@overload
def cstring(
    text: Union[str, ColorString],
    color: None = None,
    bold: Literal["BOLD", None] = None,
    /,
) -> str: ...

@overload
def os_type() -> Literal["Windows", "Linux", "BSD", "macOS"]: ...

@overload
def cpu_type() -> Literal['x64', 'ARM64']: ...

@overload
def message(text: str, /) -> None: ...
@overload
def message(mode: Literal["NOTICE"], /, text: str) -> None: ...
@overload
def message(mode: Literal["STATUS"], /, text: str, latency: float = 0.05) -> None: ...
@overload
def message(mode: Literal["REPRINT"], /, text: str) -> None: ...
@overload
def message(mode: Literal["HINT", "WARNING", "ERROR"], /, text: str) -> None: ...
@overload
def message(mode: Literal["DEPRECATED"], /, text: str) -> None: ...
@overload
def message(mode: Literal["FATAL_ERROR"], /, text: str) -> None: ...

@overload
def regedit(root_key: Literal["HKLM", "HKCU"], path: str, /, *, key_name: str) -> str | None: ...
@overload
def regedit(root_key: Literal["HKLM", "HKCU"], path: str, /, ) -> List[str] | None: ...

@overload
def subdirs(path: Path, leaf: bool = False) -> list[Path]: ...
@overload
def subdirs(path: Path, leaf: bool = True) -> list[str]: ...

@overload
def tic_toc(message: str) -> None: ...

@dataclass
class _ProgressState: ...

class ProgressTask:
    def __init__(self, display: ProgressDisplay, state: _ProgressState) -> None: ...
    def update(self, *, completed: int | None = None, stage: str | None = None) -> None: ...
    def advance(self, amount: int = 1, *, stage: str | None = None) -> None: ...
    def close(self) -> None: ...

class ProgressDisplay:
    def __init__(self, *, width: int = 24, name_width: int = 18, stream: TextIO = sys.stdout) -> None: ...
    def add(self, name: str, /, total: int, *, stage: str = "") -> ProgressTask: ...
    def close(self) -> None: ...
    def _update(self, state: _ProgressState, *, completed: int | None = None, stage: str | None = None) -> None: ...
    def _advance(self, state: _ProgressState, *, amount: int, stage: str | None = None) -> None: ...
    def _remove(self, state: _ProgressState) -> None: ...
    def _format_task(self, task: _ProgressState) -> str: ...
    def _render(self) -> None: ...
