

# SPDX-License-Identifier: MIT
# Copyright (c) 2026-${year} WEMI Contributors
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

from textwrap import dedent
from typing import Literal, Union

from utils import config
from utils.compare_functions import VersionNum
from tasks import ModulesObject

with open("version", "r", encoding="utf-8") as f:
    v = f.read().strip()

WEMI_VERSION = v


class BaseModuleTemplate:
    def __init__(self, module_obj: ModulesObject):
        self.module = module_obj
        self._lines = [
            "#%Module1.0",
            f"# Modulefile generated by wemi (Version {WEMI_VERSION})",
        ]

    def add_splitline(self):
        self._lines.append("")

    def add_modules_help(self, *content: str):
        """加入 Tcl modulefile 的標準標頭"""

        content = list(content)

        invalid_items = [item for item in content if not isinstance(item, str)]

        if invalid_items:
            bad_type = type(invalid_items[0]).__name__
            raise TypeError(
                dedent(f"""\
                WEMI raised a TypeError on add_modules_help() method.
                >>> traceback: In ModulesObject {self.module.MODULENAME}
                    Expected all argument type is str.
                    Detected invalid element type: {bad_type}
                     > {invalid_items[0]}
            """)
            )

        self._lines.append(r"proc ModulesHelp { } {")
        self._lines.extend([f'    puts stderr "{l}"' for l in content])
        self._lines.append(r"}")
        self.add_splitline()

    def add_module_whatis(self, *content: str):
        invalid_items = [item for item in content if not isinstance(item, str)]

        if invalid_items:
            bad_type = type(invalid_items[0]).__name__
            raise TypeError(
                dedent(f"""\
                WEMI raised a TypeError on add_module_whatis() method.
                >>> traceback: In ModulesObject {self.module.MODULENAME}
                    Expected all argument type is str.
                    Detected invalid element type: {bad_type}
            """)
            )

        joined_content = " ".join(content)

        self._lines.append(f'module-whatis "{joined_content}"')
        self.add_splitline()

    def add_content(self, *content: str):
        self._lines.extend(content)
        self.add_splitline()

    def add_deps(self, *deps: str):
        if deps:
            for d in deps:
                self._lines.append(f"module load {d}")
            self.add_splitline()

    def add_conflict(self, *conflicts: str):
        if isinstance(conflicts, str):
            conflicts = [conflicts]

        if config.FREE_FOR_ALL:
            return

        for c in conflicts:
            self._lines.append(f"conflict {c}")
        self.add_splitline()

    def add_llvm_conflict(self, *conflicts: str):
        if isinstance(conflicts, str):
            conflicts = [conflicts]

        if config.LLVM_CONFLICT:
            self._lines.append(
                "if { ![info exists env(DISABLE_WEMI_LLVM_CONFLICT)] } {"
            )
            for c in conflicts:
                self._lines.append(f"    conflict {c}")
            self._lines.append("}")
        self.add_splitline()

    def add_hetero_conflict(self, *conflicts: str):
        if isinstance(conflicts, str):
            conflicts = [conflicts]

        if config.HETERO_CONFLICT:
            self._lines.append(
                "if { ![info exists env(DISABLE_WEMI_HETERO_CONFLICT)] } {"
            )
            for c in conflicts:
                self._lines.append(f"    conflict {c}")
            self._lines.append("}")
        self.add_splitline()

    def add_prereq(self, *req: str):
        if req:
            for r in req:
                self._lines.append(f"prereq {r}")
            self.add_splitline()

    def add_vcompact(
        self,
        *vcompare_list: dict[Literal["env", "compare", "ver"], Union[VersionNum, str]],
    ):
        if vcompare_list:
            for v_dict in vcompare_list:
                env: str = v_dict.get("env")
                val: VersionNum | str = v_dict.get("ver")
                cond: Literal[">", ">=", "=", "<=", "<", "!=", "≠"] = v_dict.get(
                    "compare"
                )

                if cond == ">":
                    res = "== 1"
                elif cond == ">=":
                    res = ">= 0"
                elif cond == "=":
                    res = "== 0"
                elif cond == "<=":
                    res = "<= 0"
                elif cond == "<":
                    res = "== -1"
                elif cond in ("!=", "≠"):
                    res = "!= 0"
                else:
                    raise ValueError(
                        dedent(f"""\
                        prereq vcompare compare syntax occured ValueError with {cond}.

                            traceback: in modulesobject {self.module.MODULENAME}
                                > vcompare: {vcompare_list}
                        """)
                    )

                self._lines.extend(
                    [
                        f"if {{ [info exists env({env})] }} {{",
                        f'    if {{ [package vcompare $env({env}) "{val}"] {res} }} {{',
                        f'        puts stderr "vcompare error with {env} requires {val}, "',
                        f'        puts stderr "   but you have {env} = $env({env})"',
                        "        break",
                        "    }",
                        "}",
                    ]
                )
                self.add_splitline()

    def set_root(self, root: str):
        if root:
            self._lines.append(f'set root "{root}"')
            self.add_splitline()

    def set_var(self, **var_dict):
        if var_dict:
            for key, value in var_dict.items():
                self._lines.append(f'set {key} "{value}"')
            self.add_splitline()

    def set_env(self, **env_dict):
        if env_dict:
            for key, value in env_dict.items():
                self._lines.append(f'setenv {key} "{value}"')
            self.add_splitline()

    def prepend_path(self, var_name: str, /, *paths: str):
        if paths:
            if var_name == "MODULEPATH":
                self._lines.append("set MODPATH $env(MODULEPATH)")
                for p in paths:
                    self._lines.append(f'prepend-path {var_name} "$MODPATH/{p}"')
            else:
                for p in paths:
                    self._lines.append(f'prepend-path {var_name} "{p}"')
            self.add_splitline()

    def append_path(self, var_name: str, /, *paths: str):
        if paths:
            if var_name == "MODULEPATH":
                self._lines.append("set MODPATH $env(MODULEPATH)")
                for p in paths:
                    self._lines.append(f'append-path {var_name} "$MODPATH/{p}"')
            else:
                for p in paths:
                    self._lines.append(f'append-path {var_name} "{p}"')
            self.add_splitline()

    def set_cmakefile_content(self, *content: str):
        if content:
            self._lines = list(content)
            self.add_splitline()

    def build(self):
        raise NotImplementedError(
            "ModuleTemplate Subclassing must implement build() method"
        )

    def render(self) -> str:
        self.build()
        return "\n".join(self._lines) + "\n"
