name: Python 3.13 Test

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - ".ci/common/**"
      - ".ci/python-test/**"
      - ".github/workflows/_python-version-test.yaml"
      - ".github/workflows/python-3.13-test.yaml"

  pull_request:
    branches:
      - master
    paths:
      - "**.py"
      - ".ci/common/**"
      - ".ci/python-test/**"
      - ".github/workflows/_python-version-test.yaml"
      - ".github/workflows/python-3.13-test.yaml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  python-test:
    uses: ./.github/workflows/_python-version-test.yaml
    with:
      python-version: "3.13.5"
