

# SPDX-License-Identifier: MIT
# Copyright (c) 2026-${year} WEMI Contributors
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Python 3.15 Test

on:
  push:
    branches:
      - master
    paths:
      - "wemi.py"
      - "version.json"
      - ".ci/common/**"
      - ".ci/python-test/**"
      - ".github/workflows/_python-version-test.yaml"
      - ".github/workflows/python-315-test.yaml"

  pull_request:
    branches:
      - master
    paths:
      - "wemi.py"
      - "version.json"
      - ".ci/common/**"
      - ".ci/python-test/**"
      - ".github/workflows/_python-version-test.yaml"
      - ".github/workflows/python-315-test.yaml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  python-test:
    uses: ./.github/workflows/_python-version-test.yaml
    with:
      python-version: "3.15"
