name: Sync to GitCode

on:
  schedule:
    - cron: "0 4 * * *"
      timezone: "Asia/Taipei"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: mirror-gitcode
  cancel-in-progress: false

jobs:
  mirror:
    name: Push mirror to GitCode
    uses: ./.github/workflows/_sync-repo.yaml

    with:
      host: gitcode.com
      repository: TaiXeflar/wemi.git

    secrets:
      username: ${{ secrets.GITCODE_USERNAME }}
      token: ${{ secrets.GITCODE_SYNC_TOKEN }}
