

# SPDX-License-Identifier: MIT
# Copyright (c) 2026-${year} WEMI Contributors
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Sync to Gitee

on:
  schedule:
    - cron: "0 4 * * *"
      timezone: "Asia/Taipei"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: mirror-gitee
  cancel-in-progress: false

jobs:
  mirror:
    name: Push mirror to Gitee
    uses: ./.github/workflows/_sync-repo.yaml

    with:
      host: gitee.com
      repository: TaiXeflar/wemi.git

    secrets:
      username: ${{ secrets.GITEE_USERNAME }}
      token: ${{ secrets.GITEE_SYNC_TOKEN }}
