name: Sync to GitLab

on:
  schedule:
    - cron: "0 4 * * *"
      timezone: "Asia/Taipei"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: mirror-to-gitlab
  cancel-in-progress: false

jobs:
  mirror:
    name: Push mirror to GitLab
    uses: ./.github/workflows/_sync-repo.yaml

    with:
      host: gitlab.com
      repository: TaiXeflar/wemi.git
      username: oauth2

    secrets:
      token: ${{ secrets.GITLAB_SYNC_TOKEN }}
